# Generated by Django 5.1 on 2024-08-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='therapists/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Specialization_section/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='header_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_section/')),
                ('sec_image', models.ImageField(blank=True, null=True, upload_to='header_section/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='fotter_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='extra_traines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extra_traines/')),
                ('related_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='contact_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contant_section/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('button_link', models.CharField(blank=True, max_length=500, null=True)),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('address_image', models.ImageField(blank=True, null=True, upload_to='contact_info/')),
                ('phone', models.CharField(max_length=200)),
                ('phone_image', models.ImageField(blank=True, null=True, upload_to='contact_info/')),
                ('email', models.CharField(max_length=200)),
                ('email_image', models.ImageField(blank=True, null=True, upload_to='contact_info/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='certificates_sectoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='belive_and_path_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='belives/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='About_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='About_section/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='welcome_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='welcome_section_2/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='workshopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshopes/')),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('button_link', models.CharField(blank=True, max_length=500, null=True)),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
    ]
