# Generated by Django 5.1 on 2024-08-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menue_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='menue_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
                ('related_fileds', models.ManyToManyField(blank=True, to='homepage.menue_items')),
            ],
        ),
        migrations.CreateModel(
            name='upper_navvbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upper_navvbar/')),
                ('related_menue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.menue_in')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.therapist')),
            ],
        ),
    ]
