# Generated by Django 5.1 on 2024-08-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='menue_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='header_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_in/')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='menue_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meue_workshop', to='homepage.therapist')),
                ('related_fileds', models.ManyToManyField(blank=True, to='couple_workshop.menue_items')),
            ],
        ),
        migrations.CreateModel(
            name='page_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_tittle', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_section/')),
                ('page_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apear_num', models.IntegerField(default=0)),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagesec', to='homepage.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='upper_navvbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upper_navvbar/')),
                ('related_menue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='couple_workshop.menue_in')),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='homepage.therapist')),
            ],
        ),
    ]
