# Generated by Django 5.1 on 2024-08-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_workshop', '0001_initial'),
        ('homepage', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='web_details/')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apear_num', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('related_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_details', to='homepage.therapist')),
            ],
        ),
    ]
